name: Deploy to AWS Lambda Function
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check Out TestLambda Project
        uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Restore NuGet Packages
        run: nuget restore TestLambda.sln
      - name: Build Solution
        run: msbuild TestLambda.sln /p:Configuration=Release
      - name: Zip into Folder
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./
      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: GitHubActions_Lambda
          zip_file: bundle.zip
